stages:
  - lint
  - deploy

lint:
  image: node:18
  stage: lint
  script:
    - npm ci
    - npm run lint
  only:
    - main

deploy:
  image: node:18
  stage: deploy
  script:
    - npm ci
    - npm install -g firebase-tools
    - firebase deploy --token "$FIREBASE_DEPLOY_TOKEN" --project kitchen-pal-c0b19
  only:
    - main
